---
name: DBIx-Class-WebForm
version: 0.02
author:
  - |-
    Matt S. Trout
    Sebastian Riedel, C<sri@oook.de>
abstract: CRUD Methods For DBIx::Class
license: perl
requires:
  DBIx::Class: 0
  Data::FormValidator: 0
  HTML::Element: 0
provides:
  DBIx::Class::WebForm:
    file: lib/DBIx/Class/WebForm.pm
    version: 0.02
generated_by: Module::Build version 0.24
